version: '3.9'

services:
  # Use inside
  gui_next_template:
    container_name: gui_next_template
    build:
      dockerfile: Dockerfile.local
      context: ./
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env.development
    ports:
      - '4000:4000'