version: '3.9'

services:
  # Use inside
  gui_next_template:
    image: ${IMAGE_NAME}
    container_name: gui_next_template
    build:
      dockerfile: Dockerfile.production
      context: ./
    restart: always
    platform: linux/amd64
    networks:
      - lcs-internal-service-network
    env_file:
      - .env
networks:
  lcs-internal-service-network:
    external: true