FROM node:20.10.0

# Fix issue out of memory vite
ENV NODE_OPTIONS="--max-old-space-size=8192"

# Create app directory
WORKDIR /app

COPY package*.json .

COPY . .

RUN export NODE_OPTIONS=--max-old-space-size=4096

RUN npm install

EXPOSE 4000

CMD ["npm", "run", "dev"]