version: '3.9'
services:
  gui_next_template_test:
    image: '${IMAGE_NAME}'
    container_name: gui_next_template_test
    ports:
      - "${PORT}:3000"
    restart: always
    networks:
      - lcs-internal-service-network

networks:
  lcs-internal-service-network:
    external: true
